// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfZiRIhS0xL4TtvA4Tm4YsIDjIN27wnks',
    appId: '1:182414043276:web:9f99c9f01e7816dd34b3a9',
    messagingSenderId: '182414043276',
    projectId: 'meli360',
    authDomain: 'meli360.firebaseapp.com',
    storageBucket: 'meli360.firebasestorage.app',
    measurementId: 'G-LELPNDN9FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZCnajrJEB26h1r-3GwZxrdoOfuY6ZJ0',
    appId: '1:182414043276:android:2ec31eb06d36424734b3a9',
    messagingSenderId: '182414043276',
    projectId: 'meli360',
    storageBucket: 'meli360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Qq2lu7EIs1VRa5g1Jvt6w6Xaz49su0w',
    appId: '1:182414043276:ios:83892727e1d3211634b3a9',
    messagingSenderId: '182414043276',
    projectId: 'meli360',
    storageBucket: 'meli360.firebasestorage.app',
    iosBundleId: 'com.repartidor.cliente',
  );
}
